version: "3.7"
services:

  nginx:
    build:
      context: docker
      dockerfile: dev/nginx/Dockerfile
    container_name: ${APP_NAME}__nginx
    hostname: ${APP_NAME}__nginx
    volumes:
      - ./:/app
      - ./storage/logs:/var/log/nginx
    ports:
      - ${DOCKER_BRIDGE}:80:80
    restart: always

  php-fpm:
    build:
      context: docker
      dockerfile: dev/php-fpm/Dockerfile
    container_name: ${APP_NAME}__php-fpm
    hostname: ${APP_NAME}__php-fpm
    environment:
      TERM: xterm-256color
    volumes:
      - ./:/app
      - ./docker/dev/php/.bashrc:/root/.bashrc

  db:
    image: mysql:8
    container_name: ${APP_NAME}__db
    hostname: ${APP_NAME}__db
    restart: always
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DOCKER_BRIDGE}:3306:3306

    volumes:
      - ./storage/db/:/var/lib/mysql

  node:
    build:
      context: docker
      dockerfile: dev/node/Dockerfile
    container_name: ${APP_NAME}__node
    hostname: ${APP_NAME}__node
    volumes:
      - ./:/app
    tty: true

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_NETWORK}
